P8105 Homework 2
================
Emma Warshaw, UNI: ew2718
2022-10-01

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

**Problem 1**

``` r
nyc_transit_raw = 
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
           col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>%  
janitor::clean_names() %>% 
  select(
    line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, entrance_type, ada) %>% 
  mutate(
    entry = ifelse(entry == "Yes", TRUE, FALSE) 
  )
```

Is this data tidy? It’s not tidy. The route numbers should have some
kind of numeric value instead of the “NA” that’s in there now. It would
be cleaner to have “route” as a variable and fill in information with
the route number. Need to rotate the columns from wide to long.

Answer the following questions using these data:

How many distinct stations are there?

Isolate for distinct pairs based on line and staion name variables:

``` r
nyc_transit_raw %>% 
  select(line, station_name) %>% 
  distinct
```

    ## # A tibble: 465 × 2
    ##    line     station_name            
    ##    <chr>    <chr>                   
    ##  1 4 Avenue 25th St                 
    ##  2 4 Avenue 36th St                 
    ##  3 4 Avenue 45th St                 
    ##  4 4 Avenue 53rd St                 
    ##  5 4 Avenue 59th St                 
    ##  6 4 Avenue 77th St                 
    ##  7 4 Avenue 86th St                 
    ##  8 4 Avenue 95th St                 
    ##  9 4 Avenue 9th St                  
    ## 10 4 Avenue Atlantic Av-Barclays Ctr
    ## # … with 455 more rows

There are 465 distinct stations.

How many stations are ADA compliant?

Isolate in a similar way now, this time filtering for ada compliance.

``` r
nyc_transit_raw %>% 
  filter(ada == TRUE) %>% 
  select(line, station_name) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    line            station_name                  
    ##    <chr>           <chr>                         
    ##  1 4 Avenue        Atlantic Av-Barclays Ctr      
    ##  2 4 Avenue        DeKalb Av                     
    ##  3 4 Avenue        Pacific St                    
    ##  4 42nd St Shuttle Grand Central                 
    ##  5 6 Avenue        34th St                       
    ##  6 6 Avenue        47-50th Sts Rockefeller Center
    ##  7 6 Avenue        Church Av                     
    ##  8 63rd Street     21st St                       
    ##  9 63rd Street     Lexington Av                  
    ## 10 63rd Street     Roosevelt Island              
    ## # … with 74 more rows

There are 84 stations that meet this criteria

What proportion of station entrances / exits without vending allow
entrance?

``` r
nyc_transit_raw %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0

Reformat data so that route number and route name are distinct
variables. How many distinct stations serve the A train? Of the stations
that serve the A train, how many are ADA compliant?

``` r
nyc_transit_raw %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
nyc_transit_raw %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

**Problem 2**

We’ll be using an excel file, so load in the appropriate library:

``` r
library(readxl)
```

Read and clean the Mr. Trash Wheel sheet: –\> (1) specify the sheet in
the Excel file and to omit non-data entries (rows with notes / figures;
columns containing notes) using arguments in read_excel

–\> (2) use reasonable variable names

–\> (3) omit rows that do not include dumpster-specific data

–\> (4) round the number of sports balls to the nearest integer and
converts the result to an integer variable (using as.integer)

Use a similar process to import, clean, and organize the data for
Professor Trash Wheel, and combine this with the Mr. Trash Wheel dataset
to produce a single tidy dataset. To keep track of which Trash Wheel is
which, you may need to add an additional variable to both datasets
before combining.

Write a paragraph about these data; you are encouraged to use inline R.
Be sure to note the number of observations in the resulting dataset, and
give examples of key variables. For available data, what was the total
weight of trash collected by Professor Trash Wheel? What was the total
number of sports balls collected by Mr. Trash Wheel in 2020?

``` r
mr_trash = read_excel("./data/Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel") %>%
  janitor::clean_names() %>%
  select(-(x15:x16)) %>%
  drop_na(dumpster) %>%
  drop_na(month) %>% 
  mutate(
    sports_balls = round(sports_balls, digits = 0)) %>% 
  mutate(which_trash = "Mr. Trash") %>% 
  select(which_trash, everything()) %>%
  mutate(year = as.integer(year))
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
#start on professor trash
prof_trash = read_excel("./data/Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel") %>% 
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(which_trash = "Prof. Trash") %>% 
  select(which_trash, everything())

#let's combine the data sets
trash_data = full_join(mr_trash, prof_trash)
```

    ## Joining, by = c("which_trash", "dumpster", "month", "year", "date",
    ## "weight_tons", "volume_cubic_yards", "plastic_bottles", "polystyrene",
    ## "cigarette_butts", "glass_bottles", "grocery_bags", "chip_bags",
    ## "homes_powered")

``` r
#Calculate total weight of trash collected by Professor Trash Wheel
sum(prof_trash$weight_tons)
```

    ## [1] 190.12

``` r
#Calculate the total number of sports ball collected by Mr. Trash Wheel in 2020
sum(mr_trash[which(mr_trash$year == 2020), "sports_balls"])
```

    ## [1] 856

Paragraph about this data:

Professor Trash Wheel collected a total weight of 190.12 tons of trash.
In the year 2020, Mr. Trash Wheel collected a total of 856 sports balls.
The resulting combined data frame had a total is 524 observations with
15 variables. When cleaning this data, I decided to leave the year.
month, and date columns. Although there is redundant information in
this, I think it can be useful. For instance, trying to sum the number
of sports balls collected in 2020 was made easier by still having the
`year` as a variable. I could technically split the `date` variable into
corresponding pieces, but for purposes of this cleaning, I didn’t see
the merit in additional code. If I was doing more with this data set, I
might consider it if it became functionally necessary.

**Problem 3**

First, clean the data in pols-month.csv. Use separate() to break up the
variable mon into integer variables year, month, and day; replace month
number with month name; create a president variable taking values gop
and dem, and remove prez_dem and prez_gop; and remove the day variable.

``` r
pols_month = read_csv("./data/fivethirtyeight_datasets/pols-month.csv") %>%
  janitor::clean_names() %>%
  separate(col = mon, into = c('year', 'month', 'day'), sep = '-') %>%
  mutate(month = as.integer(month)) %>%
  mutate(month = case_when(
    month == 1 ~ "January",
    month == 2 ~ "February",
    month == 3 ~ "March",
    month == 4 ~ "April",
    month == 5 ~ "May",
    month == 6 ~ "June",
    month == 7 ~ "July",
    month == 8 ~ "August",
    month == 9 ~ "September",
    month == 10 ~ "October",
    month == 11 ~ "November",
    month == 12 ~ "December"
  )) %>% 
  mutate(president = case_when
         (prez_dem == 1 ~ "dem", prez_gop > 0 ~ "gop", TRUE ~ "")) %>% 
    mutate(year = as.integer(year))
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Second, clean the data in snp.csv using a similar process to the above.
For consistency across datasets, arrange according to year and month,
and organize so that year and month are the leading columns.

``` r
snp = read_csv("./data/fivethirtyeight_datasets/snp.csv") %>%
  janitor::clean_names() %>%
  separate(col = date, into = c('month', 'day', 'year'), sep = '/') %>% 
  mutate(month = case_when(
    month == 1 ~ "January",
    month == 2 ~ "February",
    month == 3 ~ "March",
    month == 4 ~ "April",
    month == 5 ~ "May",
    month == 6 ~ "June",
    month == 7 ~ "July",
    month == 8 ~ "August",
    month == 9 ~ "September",
    month == 10 ~ "October",
    month == 11 ~ "November",
    month == 12 ~ "December")
  ) %>% 
  select(-day) %>% 
  select(year, month, everything()) %>% 
  mutate(year = as.integer(year)) %>% 
  mutate(year = ifelse(year >= 50, year + 1900, year + 2000))
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Third, tidy the unemployment data so that it can be merged with the
previous datasets. This process will involve switching from “wide” to
“long” format; ensuring that key variables have the same name; and
ensuring that key variables take the same values.

``` r
unemployment_data = read_csv("./data/fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>%
  pivot_longer(jan:dec, 
               names_to = "month",
               values_to = "unemployment_percent") %>% 
  mutate(month = case_when(
    month == "jan" ~ "January",
    month == "feb" ~ "February",
    month == "mar" ~ "March",
    month == "apr" ~ "April",
    month == "may" ~ "May",
    month == "jun" ~ "June",
    month == "jul" ~ "July",
    month == "aug" ~ "August",
    month == "sep" ~ "September",
    month == "oct" ~ "October",
    month == "nov" ~ "November",
    month == "dec" ~ "December"
  ))
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Join the datasets by merging snp into pols, and merging unemployment
into the result.

``` r
combo_data = left_join(pols_month, snp, by = c("year", "month"))
combo_final = left_join(combo_data, unemployment_data, by = c("year", "month"))
```

Write a short paragraph about these datasets. Explain briefly what each
dataset contained, and describe the resulting dataset (e.g. give the
dimension, range of years, and names of key variables).

The final data set `combo_final` describes the number of elected
officials (president, governor, senator, house representative) by party
affiliation (democrat or gop), the S&P 500 closing values, and
unemployment rates for each month in the years between 1947 and 2015.
The resulting data frame has 11 variables and 822 rows. The `pols_month`
data set describes the year, month, and corresponding number of elected
officials by party affiliation. In the `pols_month` data set, the
`prez_gop` variable has a `2` as the data point for rows in the year
`1974`. This corresponds to Richard Nixon’s presidency, his removal from
office, and the start of Gerald Ford’s presidency that same year. The
`snp` data set contains the month, year, and corresponding close values
of the S&P 500. The `unemployment_data` set contains the month, year and
corresponding unemplyment percentage.
